"""create projects and conversation project_id

Revision ID: 0c83ed6e12be
Revises: 44535c03d27a
Create Date: 2026-10-02 17:43:03.987290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c83ed6e12be'
down_revision: Union[str, Sequence[str], None] = '44535c03d27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_foreign_key('conversations_project_id_fkey', 'conversations', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_project_id_fkey', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_column('conversations', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
