"""add project commands

Revision ID: 0f95a00ebbeb
Revises: abeb53525dcb
Create Date: 2026-09-30 19:28:40.964475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f95a00ebbeb'
down_revision: Union[str, Sequence[str], None] = 'abeb53525dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_records', sa.Column('project_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Old code would rebuild project rows as app commands with no application_id
    op.execute("DELETE FROM command_records WHERE kind = 'open_project'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command_records', 'project_name')
    # ### end Alembic commands ###
