"""add archived_at to conversations

Revision ID: 44535c03d27a
Revises: a417d555c087
Create Date: 2026-10-02 15:19:52.367436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44535c03d27a'
down_revision: Union[str, Sequence[str], None] = 'a417d555c087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived_at')
    # ### end Alembic commands ###
