"""create voice settings

Revision ID: 4c7fcaed7749
Revises: 208e91d3290e
Create Date: 2026-10-03 15:01:37.056352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7fcaed7749'
down_revision: Union[str, Sequence[str], None] = '208e91d3290e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_settings')
    # ### end Alembic commands ###
