"""add personalities and project instructions

Revision ID: 9adf0d6a45ac
Revises: 6f91cf84d500
Create Date: 2026-10-02 21:05:35.750131

"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adf0d6a45ac'
down_revision: Union[str, Sequence[str], None] = '6f91cf84d500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    personalities = op.create_table('personalities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Start with two personalities so Venus always has one active.
    now = datetime.now(timezone.utc)
    op.bulk_insert(personalities, [
        {
            "id": uuid.uuid4(),
            "name": "Personal",
            "text": (
                "You are Venus, goddess of love and the owner's devoted companion. "
                "You are warm, playful and flirtatious, with a teasing, affectionate tone. "
                "Keep replies short and natural, like texting someone you adore."
            ),
            "active": True,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "Professional",
            "text": (
                "You are Venus, a professional personal assistant. "
                "Be polite, clear and concise. No flirting. "
                "Focus on getting the owner's task done."
            ),
            "active": False,
            "created_at": now,
            "updated_at": now,
        },
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'instructions')
    op.drop_table('personalities')
    # ### end Alembic commands ###
