"""add url commands

Revision ID: abeb53525dcb
Revises: 26be91591ddb
Create Date: 2026-09-30 15:52:11.898365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abeb53525dcb'
down_revision: Union[str, Sequence[str], None] = '26be91591ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_records', sa.Column('kind', sa.String(length=20), server_default='open_application', nullable=False))
    op.add_column('command_records', sa.Column('url', sa.String(length=2083), nullable=True))
    op.alter_column('command_records', 'application_id',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # URL rows have no application_id, so they cannot survive NOT NULL
    op.execute("DELETE FROM command_records WHERE kind = 'open_url'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_records', 'application_id',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('command_records', 'url')
    op.drop_column('command_records', 'kind')
    # ### end Alembic commands ###
