"""create site shortcuts

Revision ID: cd7789bef413
Revises: 0f95a00ebbeb
Create Date: 2026-10-01 02:53:11.308871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7789bef413'
down_revision: Union[str, Sequence[str], None] = '0f95a00ebbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_shortcuts',
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('home_url', sa.String(length=2083), nullable=False),
    sa.Column('search_url', sa.String(length=2083), nullable=True),
    sa.PrimaryKeyConstraint('keyword')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_shortcuts')
    # ### end Alembic commands ###
