"""create owner accounts and sessions

Revision ID: dcd787205087
Revises: b1c8d2e4f709
Create Date: 2026-09-28 17:20:58.625508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd787205087'
down_revision: Union[str, Sequence[str], None] = 'b1c8d2e4f709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_accounts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('owner_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['owner_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_sessions')
    op.drop_table('owner_accounts')
    # ### end Alembic commands ###
